version: 1.0.{build}

branches:
  only:
    - release
  except:  
    - master

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

shallow_clone: true

matrix:
  fast_finish: true

platform:
  - x86

configuration:
  - Release

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: sfWumdEBETqbpMK6aVyw8w==
  nodejs_version: "7"   
  BINW32_PATH: '%APPVEYOR_BUILD_FOLDER%\..\binw32'
  PPDIR: '%APPVEYOR_BUILD_FOLDER%\..\newpascal\fpc\bin\i386-win32'
  BINW32_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/binw32.7z'
  DOWNLOAD_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/download4newpascal.js'
  LAZARUS_RUN_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/run.bat'
  NP_CONFIGURE_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/configure4pack.bat'
  NPCFT_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/np.cft'
  CCR_DOWNLOAD_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/download4ccr.js'
  CCRBIN_DOWNLOAD_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/download4ccrbin.js'
  CREATE_CFT_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/createctf.js'

# debug rdp 
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

  - rm appveyor.yml
  - npm install @octokit/rest
  - npm install download
  - npm install unzip
  - npm install concat-files

build_script:
  - appveyor DownloadFile %DOWNLOAD_DL% -FileName %APPVEYOR_BUILD_FOLDER%\download4newpascal.js
  - node download4newpascal.js
  - move %APPVEYOR_BUILD_FOLDER%\freepascal %APPVEYOR_BUILD_FOLDER%\newpascal
  - del %APPVEYOR_BUILD_FOLDER%\newpascal\configure.bat
  - appveyor DownloadFile %NP_CONFIGURE_DL% -FileName %APPVEYOR_BUILD_FOLDER%\newpascal\configure.bat
  - appveyor DownloadFile %LAZARUS_RUN_DL% -FileName %APPVEYOR_BUILD_FOLDER%\newpascal\run.bat

# !important - download this after move command freepascal -> newpascal
  - appveyor DownloadFile %BINW32_DL%
  - 7z x binw32.7z -o%APPVEYOR_BUILD_FOLDER%\newpascal -y  

  - appveyor DownloadFile %NPCFT_DL% -FileName %APPVEYOR_BUILD_FOLDER%\np.cft
  - appveyor DownloadFile %CREATE_CFT_DL% -FileName %APPVEYOR_BUILD_FOLDER%\createctf.js
  - node createctf.js

  - appveyor DownloadFile %CCR_DOWNLOAD_DL% -FileName %APPVEYOR_BUILD_FOLDER%\download4ccr.js
  - node download4ccr.js
  - md %APPVEYOR_BUILD_FOLDER%\newpascal\ccr
#  - move %APPVEYOR_BUILD_FOLDER%\generics.collections\latest %APPVEYOR_BUILD_FOLDER%\newpascal\ccr\generics.collections
  - move %APPVEYOR_BUILD_FOLDER%\mORMot\latest %APPVEYOR_BUILD_FOLDER%\newpascal\ccr\mORMot
# mORMot CCR repository (binary files for FPC - available in master)
#  - appveyor DownloadFile %CCRBIN_DOWNLOAD_DL% -FileName %APPVEYOR_BUILD_FOLDER%\download4ccrbin.js
#  - node download4ccrbin.js

after_build:
  - 7z a -tzip newpascal.zip %APPVEYOR_BUILD_FOLDER%\newpascal

#---------------------------------#
#     debug (off)                 #
#---------------------------------#

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: newpascal.zip
    name: newpascal

deploy:
  tag: np-v$(appveyor_build_version)
  release: 'NewPascal v$(appveyor_build_version)'
  description: 'Release of NewPascal'
  provider: GitHub
  auth_token:
    secure: KcYu4lP5AV4BYpPzpV2CQGucX7BpAsyRChrjOhZXH4z1DDtc5J0J6WvJ1hTr7VSI
  artifact: newpascal
  draft: true
  prerelease: false
  on:
    branch: release                # release from master branch only
    appveyor_repo_tag: false       # ?deploy on tag push only

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# deploy: off