version: 1.0.{build}

branches:
  only:
    - master


# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

shallow_clone: true

matrix:
  fast_finish: true

platform:
  - x86

configuration:
  - Release

environment:
  BINW32_PATH: '%APPVEYOR_BUILD_FOLDER%\..\binw32'
  PPDIR: '%APPVEYOR_BUILD_FOLDER%\..\newpascal\fpc\bin\i386-win32'
  BINW32_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/binw32.7z'
  DOWNLOAD_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/download4newpascalpack.js'
  SPARTA_RUN_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/run.bat'
  NP_CONFIGURE_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/configure4pack.bat'
  CCR_DOWNLOAD_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/download4ccr.js'

install:
  - rm appveyor.yml
  - appveyor DownloadFile %BINW32_DL%
  - 7z x binw32.7z -o%APPVEYOR_BUILD_FOLDER%\newpascal -y  
  - npm install github
  - npm install download
  - npm install unzip
  - appveyor DownloadFile %DOWNLOAD_DL% -FileName %APPVEYOR_BUILD_FOLDER%\download4newpascalpack.js
  - node download4newpascalpack.js

build_script:
  - del %APPVEYOR_BUILD_FOLDER%\newpascal\configure.bat
  - appveyor DownloadFile %NP_CONFIGURE_DL% -FileName %APPVEYOR_BUILD_FOLDER%\newpascal\configure.bat
  - appveyor DownloadFile %SPARTA_RUN_DL% -FileName %APPVEYOR_BUILD_FOLDER%\newpascal\run.bat

  - appveyor DownloadFile %CCR_DOWNLOAD_DL% -FileName %APPVEYOR_BUILD_FOLDER%\download4ccr.js
  - node download4ccr.js
  - md %APPVEYOR_BUILD_FOLDER%\newpascal\ccr
  - move %APPVEYOR_BUILD_FOLDER%\generics.collections\latest %APPVEYOR_BUILD_FOLDER%\newpascal\ccr\generics.collections
  - move %APPVEYOR_BUILD_FOLDER%\mORMot\latest %APPVEYOR_BUILD_FOLDER%\newpascal\ccr\mORMot

  - move %APPVEYOR_BUILD_FOLDER%\newpascal\sparta %APPVEYOR_BUILD_FOLDER%\newpascal\lazarus
  - move %APPVEYOR_BUILD_FOLDER%\newpascal %APPVEYOR_BUILD_FOLDER%\newpascalpack

after_build:
  - 7z a -tzip newpascalpack.zip %APPVEYOR_BUILD_FOLDER%\newpascalpack
  
artifacts:
  - path: newpascalpack.zip
    name: newpascalpack

deploy:
  release: newpascalpack-v$(appveyor_build_version)
  description: 'Release of NewPascal Pack'
  provider: GitHub
  auth_token:
    secure: hciZXDslu8epZhwmm/LfiZBmhbPk7BPpLd/3MOtst/uIRw2LPeAEMCXmBFikJzxQ
  artifact: newpascalpack
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false       # ?deploy on tag push only

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# deploy: off